apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  namespace: e-shop
  labels:
    app: catalog-service
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: catalog-service:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: e-shop
  labels:
    app: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
