apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: e-shop
  labels:
    app: order-service
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: dtsusecase2025.azurecr.io/order-service:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8080"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service"
            - name: CART_SERVICE_URL
              value: "http://cart-service"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: e-shop
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
